version: '3.9'
services:
  database:
    container_name: psp_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${TYPEORM_CONN_DATABASE}
      - POSTGRES_PASSWORD=${TYPEORM_CONN_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${TYPEORM_CONN_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/database
    networks:
      - psp_network
networks:
  psp_network:
    driver: bridge